"""vizly — English-first, themable charting over Apache ECharts."""

from vizly._version import __version__
from vizly.api import (
    area,
    bar,
    bar3d,
    boxplot,
    candlestick,
    chart,
    combo,
    diagram,
    donut,
    effect_scatter,
    flowchart,
    from_option,
    funnel,
    gauge,
    geo,
    graph,
    grid,
    heatmap,
    kline,
    line,
    line3d,
    liquid,
    map,
    map_chart,
    mix,
    page,
    parallel,
    pictorial_bar,
    pie,
    polar,
    radar,
    sankey,
    scatter,
    scatter3d,
    sunburst,
    surface3d,
    tab,
    theme_river,
    timeline,
    tree,
    treemap,
    waterfall,
    wordcloud,
)
from vizly.base import BaseChart, OptionChart
from vizly.charts import list_chart_types, list_unavailable_chart_types
from vizly.config import get_theme, resolve_theme, set_theme
from vizly.data import (
    DataError,
    TabularView,
    as_tabular,
    filter_tabular,
    infer_roles,
    standardize,
)
from vizly.events import build_click_payload, filter_by_click
from vizly.geo_layers import GeoLayer, overlay_geojson
from vizly.loaders import (
    from_columnar,
    from_csv,
    from_excel,
    from_json,
    from_records,
    from_sql,
    from_tsv,
)
from vizly.maps import list_bundled_maps, list_opt_in_maps, register_map_pack
from vizly.metrics import from_cloudwatch, from_elasticsearch, from_elk, from_prometheus
from vizly.render import load_map_geojson, map_path
from vizly.theme.registry import (
    export_theme,
    list_themes,
    load_theme,
    register_theme,
)

__all__ = [
    "BaseChart",
    "DataError",
    "GeoLayer",
    "OptionChart",
    "TabularView",
    "__version__",
    "area",
    "as_tabular",
    "bar",
    "bar3d",
    "boxplot",
    "build_click_payload",
    "candlestick",
    "chart",
    "combo",
    "diagram",
    "donut",
    "effect_scatter",
    "export_theme",
    "filter_by_click",
    "filter_tabular",
    "flowchart",
    "from_cloudwatch",
    "from_columnar",
    "from_csv",
    "from_elasticsearch",
    "from_elk",
    "from_excel",
    "from_json",
    "from_option",
    "from_prometheus",
    "from_records",
    "from_sql",
    "from_tsv",
    "funnel",
    "gauge",
    "geo",
    "get_theme",
    "graph",
    "grid",
    "heatmap",
    "infer_roles",
    "kline",
    "line",
    "line3d",
    "liquid",
    "list_bundled_maps",
    "list_chart_types",
    "list_opt_in_maps",
    "list_themes",
    "list_unavailable_chart_types",
    "load_map_geojson",
    "load_theme",
    "map",
    "map_chart",
    "map_path",
    "mix",
    "overlay_geojson",
    "page",
    "parallel",
    "pictorial_bar",
    "pie",
    "polar",
    "radar",
    "register_map_pack",
    "register_theme",
    "resolve_theme",
    "sankey",
    "scatter",
    "scatter3d",
    "set_theme",
    "standardize",
    "sunburst",
    "surface3d",
    "tab",
    "theme_river",
    "timeline",
    "tree",
    "treemap",
    "waterfall",
    "wordcloud",
]
